### ISSUE TITLE
Do the plugin work for graylog 2.3?

### ISSUE THREAD

**Issue by kieulam141** [graylog-labs/graylog-plugin-dnsresolver#2]
Hi,
Our cluster using version 2.3.x.Do this plugin support for our cluster version?
Thanks.

**Comment by joschi** [comment]
I don't know about Graylog 2.3.0, but version 1.2.0 of this plugin is compatible with Graylog 2.4.0:
https://github.com/graylog-labs/graylog-plugin-dnsresolver/releases/tag/1.2.0
